apiVersion: v1
kind: Service
metadata:
  name: language-app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: meine-saetze
  ports:
    - name: http
      port: 80
      targetPort: http
